---
label: Default
hide_body: false
is_partial: false
fields:
- name: image
  label: Image
  type: text
  hidden: false
  default: "/images/happenmeta.jpg"
pages:
- _posts/show-and-tell-bringing-artificial-intelligence-to-life.md
